### ISSUE TITLE
Trying to castle by clicking on King then on rook crashes program

### ISSUE THREAD

**Issue by JuggleHacker** [fsmosca/Python-Easy-Chess-GUI#48]
Trying to castle by clicking on King then on rook crashes program.
Stack trace:
Traceback (most recent call last):
  File "*\python_easy_chess_gui.py", line 3578, in <module>
    main()
  File "*\python_easy_chess_gui.py", line 3574, in main
    pecg.main_loop()
  File "*\python_easy_chess_gui.py", line 3535, in main_loop
    start_new_game = self.play_game(window, engine_id_name, board)
  File "*\python_easy_chess_gui.py", line 2055, in play_game
    self.update_rook(window, str(user_move))
  File "*\python_easy_chess_gui.py", line 1543, in update_rook
    self.psg_board[self.get_row(fr)][self.get_col(fr)] = BLANK
UnboundLocalError: local variable 'fr' referenced before assignment

**Comment by fsmosca** [comment]
Thanks, to castle, use e1g1 or e1c1 or e8g8 or e8c8.

I will try to fix it not to crash.
